### ISSUE TITLE
Issue when inspecting specific entity instance of my meta-model

### ISSUE THREAD

**Issue by juliendelplanque** [pavel-krivanek/Moose-obsolete#10]
To try to bypass issue #9, I called `#entities` on the MooseModel to get the list of entities and inspect it.

When I click on a specific entity in the list, I get the exception `Instance of ... does not understand #metamodel`

![capture d ecran 2018-02-15 a 14 17 56](https://user-images.githubusercontent.com/8260456/36258519-3d30702a-125b-11e8-98a1-758feb22dfc4.png)

**Comment by pavel-krivanek** [comment]
Can be reproduced more simply using:
```
MooseGroup with: 1
```

**Comment by juliendelplanque** [comment]
So, do you think it comes from my usage of FamixNG?

**Comment by pavel-krivanek** [comment]
no, it is an issue related to the splitting of metamodels while there was only one in the old Famix

**Comment by pavel-krivanek** [comment]
hmm, I was wrong, with MooseGroup it is a slightly different issue, your model classes are not generating the #metamodel message. Checking why...

**Comment by pavel-krivanek** [comment]
to fix it, you need to set the generator for your builder, something like this:
```
	builder := FamixMetamodelBuilder new.
	builder
		packageName: self class packageName;
		prefix: self class prefix;
		generator: self;
		traitsFlattening: true
```
It will then be used as the source of the metamodel
