### ISSUE TITLE
Can not inspect an entity of the meta-model.

### ISSUE THREAD

**Issue by juliendelplanque** [pavel-krivanek/Moose-obsolete#5]
I am writing the script that build a model from a PostgreSQL DB and I can not inspect the entities of the model, I got the following exception:

<img width="1105" alt="capture d ecran 2018-01-09 a 17 08 38" src="https://user-images.githubusercontent.com/8260456/34730455-c70e6392-f55f-11e7-9628-6d92d36d77f2.png">

**Comment by pavel-krivanek** [comment]
this particular failure fixed in 0c4f32207d6ac6bb7086262dbc6f50a4fcf52314
