### ISSUE TITLE
Where symbols should be provided as parameter, check symbols are provided

### ISSUE THREAD

**Issue by juliendelplanque** [pavel-krivanek/Moose-obsolete#7]
I wrote this:
```
(storedProcedureCall as: #TStoredProcedure property: #parameters)
		<>-*
(reference as: #TReference property: storedProcedure)
```

Instead of this:
```
(storedProcedureCall as: #TStoredProcedure property: #parameters)
		<>-*
(reference as: #TReference property: #storedProcedure)
```

And finding the mistake was not easy given the exception I had : 
![instance of famixmetamodelbuilderclass did not understand assymbol](https://user-images.githubusercontent.com/8260456/35904483-8de617aa-0be3-11e8-94be-ffa9419d6e4f.png)

**Comment by pavel-krivanek** [comment]
solved in 523ddcd793ed6743d8514841313a933eecca30f0
